name: Followers Metrics
on:
  schedule:
    - cron: "0 0 * * *" # يحدث يومياً
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AMR2010M
          template: classic
          base: "" # نتركها فارغة لنركز فقط على المتابعين
          plugin_followers: yes
          plugin_followers_limit: 10 # عدد المتابعين الذين تريد إظهار صورهم
          filename: github-followers.svg
