name: Update Followers
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Followers
        uses: AMR2010M/unwrap-followers@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: AMR2010M
          
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update followers list"
