name: Latest Followers

on:
  schedule:
    # يعمل الكود كل 6 ساعات لتحديث القائمة
    - cron: '0 */4 * * *'
  workflow_dispatch: # يسمح لك بتشغيله يدوياً

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # هذا الرابط يجلب آخر متابعيك من جيت هب بصيغة RSS
          feed_list: "https://api.github.com/users/AMR2010M/followers"
          # سنقوم بتخصيص التصميم ليظهر كقائمة متابعين
          template: "- <a href='$url'><img src='$url.png' width='30' height='30' style='border-radius:50%'> $title</a>"
          max_post_count: 4
          comment_tag_name: "FOLLOWERS"
